# Generated by Django 4.1.7 on 2023-07-26 18:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название кондитерской')),
                ('address', models.CharField(max_length=250, verbose_name='адрес кондитерской')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='номер телефона кондитерской')),
            ],
            options={
                'verbose_name': 'пекарня',
                'verbose_name_plural': 'пекарни',
            },
        ),
        migrations.CreateModel(
            name='CakeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название категории')),
            ],
            options={
                'verbose_name': 'категория торта',
                'verbose_name_plural': 'категории тортов',
            },
        ),
        migrations.CreateModel(
            name='CatalogCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название торта')),
                ('description', models.TextField(verbose_name='описание торта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение торта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cake_app.cakecategory')),
            ],
            options={
                'verbose_name': 'каталожный торт',
                'verbose_name_plural': 'каталожные торты',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название компонента')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'компоненты',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название типа')),
            ],
            options={
                'verbose_name': 'тип компонента',
                'verbose_name_plural': 'типы компонентов',
            },
        ),
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=250, verbose_name='адрес доставки')),
                ('delivery_datetime', models.DateTimeField(db_index=True, verbose_name='время доставки')),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='доставили')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий курьеру')),
            ],
            options={
                'verbose_name': 'доставка',
                'verbose_name_plural': 'доставки',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLACED', 'Оформлен'), ('DELIVERED', 'Доставляется'), ('TAKEN', 'Получен')], db_index=True, default='PLACED', max_length=15, verbose_name='статус заказа')),
                ('client_name', models.CharField(max_length=100, verbose_name='имя клиента')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='почта клиента')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий к заказу')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='заказ зарегестрирован')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='заказ выполнен')),
                ('bakery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cake_app.bakery', verbose_name='лавка самовывоза')),
                ('delivery', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='cake_app.delivery', verbose_name='доставка')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('inscription', models.TextField(blank=True, help_text='заполняется для компонента "надпись"', verbose_name='надпись на торт')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена в заказе')),
                ('catalog_cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='cake_app.catalogcake', verbose_name='торт из каталога')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='cake_app.component', verbose_name='компонент торта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cake_app.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'состав заказа',
                'verbose_name_plural': 'состав заказа',
            },
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cake_app.componenttype'),
        ),
    ]
