# Generated by Django 4.1.7 on 2023-07-30 19:32

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название кондитерской')),
                ('address', models.CharField(max_length=250, verbose_name='адрес кондитерской')),
                ('contact_phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='номер телефона кондитерской')),
            ],
            options={
                'verbose_name': 'пекарня',
                'verbose_name_plural': 'пекарни',
            },
        ),
        migrations.CreateModel(
            name='Berries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'ягода',
                'verbose_name_plural': 'ягоды',
            },
        ),
        migrations.CreateModel(
            name='CakeCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название категории')),
                ('image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='изображение для категории')),
            ],
            options={
                'verbose_name': 'категория торта',
                'verbose_name_plural': 'категории тортов',
            },
        ),
        migrations.CreateModel(
            name='CatalogCake',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название торта')),
                ('description', models.TextField(verbose_name='описание торта')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
                ('image', models.ImageField(upload_to='', verbose_name='изображение торта')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cake_app.cakecategory', verbose_name='категория торта')),
            ],
            options={
                'verbose_name': 'торт из каталога',
                'verbose_name_plural': 'каталог тортов',
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название компонента')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'компонент',
                'verbose_name_plural': 'компоненты',
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='название типа')),
            ],
            options={
                'verbose_name': 'тип компонента',
                'verbose_name_plural': 'типы компонентов',
            },
        ),
        migrations.CreateModel(
            name='Decors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'декор',
                'verbose_name_plural': 'декоры',
            },
        ),
        migrations.CreateModel(
            name='Forms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'форма',
                'verbose_name_plural': 'формы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PLACED', 'Оформлен'), ('DELIVERED', 'Доставляется'), ('COMPLETE', 'Готов к выдаче'), ('TAKEN', 'Получен')], db_index=True, default='PLACED', max_length=15, verbose_name='статус заказа')),
                ('client_name', models.CharField(max_length=100, verbose_name='имя клиента')),
                ('phonenumber', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='RU', verbose_name='номер телефона')),
                ('email', models.EmailField(max_length=254, verbose_name='почта клиента')),
                ('comment', models.TextField(blank=True, verbose_name='комментарий к заказу')),
                ('inscription', models.TextField(blank=True, verbose_name='надпись на торт')),
                ('order_receipt_method', models.CharField(choices=[('DELIVERY', 'Доставка'), ('PICKUP', 'Самовывоз')], db_index=True, default='PICKUP', max_length=15, verbose_name='Способ получения заказа')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='адрес доставки')),
                ('delivery_datetime', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата и время доставки')),
                ('delivered_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='доставили')),
                ('delivery_comment', models.TextField(blank=True, verbose_name='комментарий курьеру')),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='заказ зарегестрирован')),
                ('completed_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='заказ выполнен')),
                ('total_cost', models.IntegerField(blank=True, null=True, verbose_name='Стоимость заказа')),
                ('bakery', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cake_app.bakery', verbose_name='кондитерская для самовывоза')),
                ('cake_berry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake_app.berries', verbose_name='заказ')),
                ('cake_decor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake_app.decors', verbose_name='заказ')),
                ('cake_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake_app.forms', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'заказ',
                'verbose_name_plural': 'заказы',
            },
        ),
        migrations.CreateModel(
            name='Sizes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'размер',
                'verbose_name_plural': 'размеры',
            },
        ),
        migrations.CreateModel(
            name='Toppings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена')),
            ],
            options={
                'verbose_name': 'топпинг',
                'verbose_name_plural': 'топпинги',
            },
        ),
        migrations.CreateModel(
            name='OrderComponents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена в заказе')),
                ('component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_components', to='cake_app.component', verbose_name='компонент торта')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cake_app.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'ингридиенты в заказе',
                'verbose_name_plural': 'ингридиенты в заказе',
            },
        ),
        migrations.CreateModel(
            name='OrderCatalogCakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена в заказе')),
                ('catalog_cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_cakes', to='cake_app.catalogcake', verbose_name='торт из каталога')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cake_app.order', verbose_name='заказ')),
            ],
            options={
                'verbose_name': 'торты из каталога в заказе',
                'verbose_name_plural': 'торты из каталога в заказе',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='cake_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake_app.sizes', verbose_name='заказ'),
        ),
        migrations.AddField(
            model_name='order',
            name='cake_topping',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='cake_app.toppings', verbose_name='заказ'),
        ),
        migrations.AddField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cake_app.componenttype', verbose_name='тип компонента'),
        ),
    ]
