# Generated by Django 4.1.7 on 2023-07-27 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0002_cakecategory_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='delivery',
        ),
        migrations.AddField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=250, verbose_name='адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='доставили'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_comment',
            field=models.TextField(blank=True, verbose_name='комментарий курьеру'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_datetime',
            field=models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='дата и время доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_receipt_method',
            field=models.CharField(choices=[('DELIVERY', 'Доставка'), ('PICKUP', 'Самовывоз')], db_index=True, default='PICKUP', max_length=15, verbose_name='Способ получения заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='bakery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cake_app.bakery', verbose_name='кондитерская для самовывоза'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('PLACED', 'Оформлен'), ('DELIVERED', 'Доставляется'), ('COMPLETE', 'Готов к выдаче'), ('TAKEN', 'Получен')], db_index=True, default='PLACED', max_length=15, verbose_name='статус заказа'),
        ),
        migrations.DeleteModel(
            name='Delivery',
        ),
    ]
