# Generated by Django 4.1.7 on 2023-07-27 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0003_remove_order_delivery_order_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='catalogcake',
            options={'verbose_name': 'торт из каталога', 'verbose_name_plural': 'каталог тортов'},
        ),
    ]
