# Generated by Django 4.1.7 on 2023-07-29 06:21

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0004_alter_catalogcake_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitems',
            name='catalog_cake',
        ),
        migrations.CreateModel(
            name='OrderCatalogCakes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='количество')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='цена в заказе')),
                ('catalog_cake', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='cake_app.catalogcake', verbose_name='торт из каталога')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cake_app.order', verbose_name='заказ')),
            ],
        ),
    ]
