# Generated by Django 4.1.7 on 2023-07-29 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0006_ordercomponents_order_inscription_delete_orderitems_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordercatalogcakes',
            options={'verbose_name': 'торты из каталога в заказе', 'verbose_name_plural': 'торты из каталога в заказе'},
        ),
        migrations.AlterModelOptions(
            name='ordercomponents',
            options={'verbose_name': 'ингридиенты в заказе', 'verbose_name_plural': 'ингридиенты в заказе'},
        ),
        migrations.AlterField(
            model_name='catalogcake',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cakes', to='cake_app.cakecategory', verbose_name='категория торта'),
        ),
        migrations.AlterField(
            model_name='component',
            name='component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cake_app.componenttype', verbose_name='тип компонента'),
        ),
    ]
