# Generated by Django 4.1.7 on 2023-07-29 14:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cake_app', '0007_alter_ordercatalogcakes_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordercatalogcakes',
            name='catalog_cake',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_cakes', to='cake_app.catalogcake', verbose_name='торт из каталога'),
        ),
        migrations.AlterField(
            model_name='ordercomponents',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_components', to='cake_app.component', verbose_name='компонент торта'),
        ),
        migrations.AlterField(
            model_name='ordercomponents',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='cake_app.order', verbose_name='заказ'),
        ),
    ]
